"function"!==typeof window.DIL&&(window.DIL=function(a,b){var e=[],d,g;a!==Object(a)&&(a={});var h,k,r,v,s,n,w,E,t,A,L,B,C,F;h=a.partner;k=a.containerNSID;r=!!a.disableDestinationPublishingIframe;v=a.iframeAkamaiHTTPS;s=a.mappings;n=a.uuidCookie;w=!0===a.enableErrorReporting;E=a.visitorService;t=a.declaredId;A=!0===a.removeFinishedScriptsAndCallbacks;L=!0===a.delayAllUntilWindowLoad;B=!0===a.disableIDSyncs;C="undefined"===typeof a.secureDataCollection||!0===a.secureDataCollection;F=!0===a.useCORSOnly;
var M,N,I,G,O,P,Q,R;M=!0===a.disableScriptAttachment;N=!0===a.disableDefaultRequest;I=a.afterResultForDefaultRequest;G=a.dpIframeSrc;O=!0===a.testCORS;P=!0===a.useJSONPOnly;Q=a.visitorConstructor;R=!0===a.disableCORS;w&&DIL.errorModule.activate();var T=!0===window._dil_unit_tests;(d=b)&&e.push(d+"");if(!h||"string"!==typeof h)return d="DIL partner is invalid or not specified in initConfig",DIL.errorModule.handleError({name:"error",message:d,filename:"dil.js"}),Error(d);d="DIL containerNSID is invalid or not specified in initConfig, setting to default of 0";
if(k||"number"===typeof k)k=parseInt(k,10),!isNaN(k)&&0<=k&&(d="");d&&(k=0,e.push(d),d="");g=DIL.getDil(h,k);if(g instanceof DIL&&g.api.getPartner()===h&&g.api.getContainerNSID()===k)return g;if(this instanceof DIL)DIL.registerDil(this,h,k);else return new DIL(a,"DIL was not instantiated with the 'new' operator, returning a valid instance with partner \x3d "+h+" and containerNSID \x3d "+k);var z={IS_HTTPS:C||"https:"===document.location.protocol,POST_MESSAGE_ENABLED:!!window.postMessage,COOKIE_MAX_EXPIRATION_DATE:"Tue, 19 Jan 2038 03:14:07 UTC"},
J={stuffed:{}},p={},q={firingQueue:[],fired:[],firing:!1,sent:[],errored:[],reservedKeys:{sids:!0,pdata:!0,logdata:!0,callback:!0,postCallbackFn:!0,useImageRequest:!0},callbackPrefix:"demdexRequestCallback",firstRequestHasFired:!1,useJSONP:!0,abortRequests:!1,num_of_jsonp_responses:0,num_of_jsonp_errors:0,num_of_cors_responses:0,num_of_cors_errors:0,corsErrorSources:[],num_of_img_responses:0,num_of_img_errors:0,toRemove:[],removed:[],readyToRemove:!1,platformParams:{d_nsid:k+"",d_rtbd:"json",d_jsonv:DIL.jsonVersion+
"",d_dst:"1"},nonModStatsParams:{d_rtbd:!0,d_dst:!0,d_cts:!0,d_rs:!0},modStatsParams:null,adms:{TIME_TO_CATCH_ALL_REQUESTS_RELEASE:2E3,calledBack:!1,mid:null,noVisitorAPI:!1,VisitorAPI:null,instance:null,releaseType:"no VisitorAPI",isOptedOut:!0,isOptedOutCallbackCalled:!1,admsProcessingStarted:!1,process:function(c){try{if(!this.admsProcessingStarted){this.admsProcessingStarted=!0;var m=this,l,f,a,d;if("function"===typeof c&&"function"===typeof c.getInstance){if(E===Object(E)&&(l=E.namespace)&&"string"===
typeof l)f=c.getInstance(l,{idSyncContainerID:k});else{this.releaseType="no namespace";this.releaseRequests();return}if(f===Object(f)&&f instanceof c&&"function"===typeof f.isAllowed&&"function"===typeof f.getMarketingCloudVisitorID&&"function"===typeof f.getCustomerIDs&&"function"===typeof f.isOptedOut){this.VisitorAPI=c;if(!f.isAllowed()){this.releaseType="VisitorAPI not allowed";this.releaseRequests();return}this.instance=f;a=function(c){"VisitorAPI"!==m.releaseType&&(m.mid=c,m.releaseType="VisitorAPI",
m.releaseRequests())};d=f.getMarketingCloudVisitorID(a);if("string"===typeof d&&d.length){a(d);return}setTimeout(function(){"VisitorAPI"!==m.releaseType&&(m.releaseType="timeout",m.releaseRequests())},this.TIME_TO_CATCH_ALL_REQUESTS_RELEASE);return}this.releaseType="invalid instance"}else this.noVisitorAPI=!0;this.releaseRequests()}}catch(b){this.releaseRequests()}},releaseRequests:function(){this.calledBack=!0;q.registerRequest()},getMarketingCloudVisitorID:function(){return this.instance?this.instance.getMarketingCloudVisitorID():
null},getMIDQueryString:function(){var c=x.isPopulatedString,m=this.getMarketingCloudVisitorID();if(!c(this.mid)||this.mid!==m)this.mid=m;return c(this.mid)?"d_mid\x3d"+this.mid+"\x26":""},getCustomerIDs:function(){return this.instance?this.instance.getCustomerIDs():null},getCustomerIDsQueryString:function(c){if(c===Object(c)){var m="",l=[],f=[],a,d;for(a in c)c.hasOwnProperty(a)&&(f[0]=a,d=c[a],d===Object(d)&&(f[1]=d.id||"",f[2]=d.authState||0,l.push(f),f=[]));if(f=l.length)for(c=0;c<f;c++)m+="\x26d_cid_ic\x3d"+
u.encodeAndBuildRequest(l[c],"%01");return m}return""},getIsOptedOut:function(){this.instance?this.instance.isOptedOut([this,this.isOptedOutCallback],this.VisitorAPI.OptOut.GLOBAL,!0):(this.isOptedOut=!1,this.isOptedOutCallbackCalled=!0)},isOptedOutCallback:function(c){this.isOptedOut=c;this.isOptedOutCallbackCalled=!0;q.registerRequest()}},declaredId:{declaredId:{init:null,request:null},declaredIdCombos:{},setDeclaredId:function(c,m){var l=x.isPopulatedString,f=encodeURIComponent;if(c===Object(c)&&
l(m)){var a=c.dpid,d=c.dpuuid,b=null;if(l(a)&&l(d)){b=f(a)+"$"+f(d);if(!0===this.declaredIdCombos[b])return"setDeclaredId: combo exists for type '"+m+"'";this.declaredIdCombos[b]=!0;this.declaredId[m]={dpid:a,dpuuid:d};return"setDeclaredId: succeeded for type '"+m+"'"}}return"setDeclaredId: failed for type '"+m+"'"},getDeclaredIdQueryString:function(){var c=this.declaredId.request,m=this.declaredId.init,a=encodeURIComponent,f="";null!==c?f="\x26d_dpid\x3d"+a(c.dpid)+"\x26d_dpuuid\x3d"+a(c.dpuuid):
null!==m&&(f="\x26d_dpid\x3d"+a(m.dpid)+"\x26d_dpuuid\x3d"+a(m.dpuuid));return f}},registerRequest:function(c){var m=this.firingQueue;c===Object(c)&&m.push(c);if(!this.firing&&m.length&&(!L||DIL.windowLoaded))if(this.adms.isOptedOutCallbackCalled||this.adms.getIsOptedOut(),this.adms.calledBack&&(!this.adms.isOptedOut&&this.adms.isOptedOutCallbackCalled)&&(this.adms.isOptedOutCallbackCalled=!1,c=m.shift(),c.src=c.src.replace(/demdex.net\/event\?d_nsid=/,"demdex.net/event?"+this.adms.getMIDQueryString()+
"d_nsid\x3d"),x.isPopulatedString(c.corsPostData)&&(c.corsPostData=c.corsPostData.replace(/^d_nsid=/,this.adms.getMIDQueryString()+"d_nsid\x3d")),D.fireRequest(c),!this.firstRequestHasFired&&("script"===c.tag||"cors"===c.tag)))this.firstRequestHasFired=!0},processVisitorAPI:function(){this.adms.process(Q||window.Visitor)},requestRemoval:function(c){if(!A)return"removeFinishedScriptsAndCallbacks is not boolean true";var m=this.toRemove,a,f;c===Object(c)&&(a=c.script,f=c.callbackName,(a===Object(a)&&
"SCRIPT"===a.nodeName||"no script created"===a)&&("string"===typeof f&&f.length)&&m.push(c));if(this.readyToRemove&&m.length){f=m.shift();a=f.script;f=f.callbackName;"no script created"!==a?(c=a.src,a.parentNode.removeChild(a)):c=a;window[f]=null;try{delete window[f]}catch(d){}this.removed.push({scriptSrc:c,callbackName:f});DIL.variables.scriptsRemoved.push(c);DIL.variables.callbacksRemoved.push(f);return this.requestRemoval()}return"requestRemoval() processed"}};g=function(){var c="http://fast.",
m="?d_nsid\x3d"+k+"#"+encodeURIComponent(document.location.href);if("string"===typeof G&&G.length)return G+m;z.IS_HTTPS&&(c=!0===v?"https://fast.":"https://");return c+h+".demdex.net/dest5.html"+m};var y={THROTTLE_START:3E4,throttleTimerSet:!1,id:"destination_publishing_iframe_"+h+"_"+k,url:g(),iframe:null,iframeHasLoaded:!1,sendingMessages:!1,messages:[],messagesPosted:[],messageSendingInterval:z.POST_MESSAGE_ENABLED?15:100,ibsDeleted:[],jsonProcessed:[],newIframeCreated:null,iframeIdChanged:!1,
originalIframeHasLoadedAlready:null,attachIframe:function(){function c(){f=document.createElement("iframe");f.sandbox="allow-scripts allow-same-origin";f.title="Adobe ID Syncing iFrame";f.id=a.id;f.style.cssText="display: none; width: 0; height: 0;";f.src=a.url;a.newIframeCreated=!0;m();document.body.appendChild(f)}function m(){u.addListener(f,"load",function(){f.className="aamIframeLoaded";a.iframeHasLoaded=!0;a.requestToProcess()})}var a=this,f=document.getElementById(this.id);f?"IFRAME"!==f.nodeName?
(this.id+="_2",this.iframeIdChanged=!0,c()):(this.newIframeCreated=!1,"aamIframeLoaded"!==f.className?(this.originalIframeHasLoadedAlready=!1,m()):(this.iframeHasLoaded=this.originalIframeHasLoadedAlready=!0,this.iframe=f,this.requestToProcess())):c();this.iframe=f},requestToProcess:function(c,a){var l=this;c&&!x.isEmptyObject(c)&&this.process(c,a);this.iframeHasLoaded&&(this.messages.length&&!this.sendingMessages)&&(this.throttleTimerSet||(this.throttleTimerSet=!0,setTimeout(function(){l.messageSendingInterval=
z.POST_MESSAGE_ENABLED?15:150},this.THROTTLE_START)),this.sendingMessages=!0,this.sendMessages())},process:function(c,a){var l=encodeURIComponent,f,d,b,e,h,g;a===Object(a)&&(g=u.encodeAndBuildRequest(["",a.dpid||"",a.dpuuid||""],","));if((f=c.dests)&&f instanceof Array&&(d=f.length))for(b=0;b<d;b++)e=f[b],e=[l("dests"),l(e.id||""),l(e.y||""),l(e.c||"")],this.addMessage(e.join("|"));if((f=c.ibs)&&f instanceof Array&&(d=f.length))for(b=0;b<d;b++)e=f[b],e=[l("ibs"),l(e.id||""),l(e.tag||""),u.encodeAndBuildRequest(e.url||
[],","),l(e.ttl||""),"",g],this.addMessage(e.join("|"));if((f=c.dpcalls)&&f instanceof Array&&(d=f.length))for(b=0;b<d;b++)e=f[b],h=e.callback||{},h=[h.obj||"",h.fn||"",h.key||"",h.tag||"",h.url||""],e=[l("dpm"),l(e.id||""),l(e.tag||""),u.encodeAndBuildRequest(e.url||[],","),l(e.ttl||""),u.encodeAndBuildRequest(h,","),g],this.addMessage(e.join("|"));this.jsonProcessed.push(c)},addMessage:function(c){var a=encodeURIComponent,a=w?a("---destpub-debug---"):a("---destpub---");this.messages.push(a+c)},
sendMessages:function(){var c=this,a;this.messages.length?(a=this.messages.shift(),DIL.xd.postMessage(a,this.url,this.iframe.contentWindow),this.messagesPosted.push(a),setTimeout(function(){c.sendMessages()},this.messageSendingInterval)):this.sendingMessages=!1}},K={traits:function(c){x.isValidPdata(c)&&(p.sids instanceof Array||(p.sids=[]),u.extendArray(p.sids,c));return this},pixels:function(c){x.isValidPdata(c)&&(p.pdata instanceof Array||(p.pdata=[]),u.extendArray(p.pdata,c));return this},logs:function(c){x.isValidLogdata(c)&&
(p.logdata!==Object(p.logdata)&&(p.logdata={}),u.extendObject(p.logdata,c));return this},customQueryParams:function(c){x.isEmptyObject(c)||u.extendObject(p,c,q.reservedKeys);return this},signals:function(c,a){var l,f=c;if(!x.isEmptyObject(f)){if(a&&"string"===typeof a)for(l in f={},c)c.hasOwnProperty(l)&&(f[a+l]=c[l]);u.extendObject(p,f,q.reservedKeys)}return this},declaredId:function(c){q.declaredId.setDeclaredId(c,"request");return this},result:function(c){"function"===typeof c&&(p.callback=c);
return this},afterResult:function(c){"function"===typeof c&&(p.postCallbackFn=c);return this},useImageRequest:function(){p.useImageRequest=!0;return this},clearData:function(){p={};return this},submit:function(){D.submitRequest(p);p={};return this},getPartner:function(){return h},getContainerNSID:function(){return k},getEventLog:function(){return e},getState:function(){var c={},m={};u.extendObject(c,q,{callbackPrefix:!0,useJSONP:!0,registerRequest:!0});u.extendObject(m,y,{attachIframe:!0,requestToProcess:!0,
process:!0,sendMessages:!0});return{initConfig:a,pendingRequest:p,otherRequestInfo:c,destinationPublishingInfo:m}},idSync:function(c){if(B)return"Error: id syncs have been disabled";if(c!==Object(c)||"string"!==typeof c.dpid||!c.dpid.length)return"Error: config or config.dpid is empty";if("string"!==typeof c.url||!c.url.length)return"Error: config.url is empty";var a=c.url,l=c.minutesToLive,f=encodeURIComponent,d,a=a.replace(/^https:/,"").replace(/^http:/,"");if("undefined"===typeof l)l=20160;else if(l=
parseInt(l,10),isNaN(l)||0>=l)return"Error: config.minutesToLive needs to be a positive number";d=u.encodeAndBuildRequest(["",c.dpid,c.dpuuid||""],",");c=["ibs",f(c.dpid),"img",f(a),l,"",d];y.addMessage(c.join("|"));q.firstRequestHasFired&&y.requestToProcess();return"Successfully queued"},aamIdSync:function(c){if(B)return"Error: id syncs have been disabled";if(c!==Object(c)||"string"!==typeof c.dpuuid||!c.dpuuid.length)return"Error: config or config.dpuuid is empty";c.url="//dpm.demdex.net/ibs:dpid\x3d"+
c.dpid+"\x26dpuuid\x3d"+c.dpuuid;return this.idSync(c)},passData:function(c){if(x.isEmptyObject(c))return"Error: json is empty or not an object";y.ibsDeleted.push(c.ibs);delete c.ibs;D.defaultCallback(c);return c},getPlatformParams:function(){return q.platformParams},getEventCallConfigParams:function(){var c=q,a=c.modStatsParams,l=c.platformParams,f;if(!a){a={};for(f in l)l.hasOwnProperty(f)&&!c.nonModStatsParams[f]&&(a[f.replace(/^d_/,"")]=l[f]);c.modStatsParams=a}return a}},D={corsMetadata:function(){var c=
"none",a=!0;"undefined"!==typeof XMLHttpRequest&&XMLHttpRequest===Object(XMLHttpRequest)&&("withCredentials"in new XMLHttpRequest?c="XMLHttpRequest":(new Function("/*@cc_on return /^10/.test(@_jscript_version) @*/"))()?c="XMLHttpRequest":"undefined"!==typeof XDomainRequest&&XDomainRequest===Object(XDomainRequest)&&(a=!1),0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor")&&(a=!1));return{corsType:c,corsCookiesEnabled:a}}(),getCORSInstance:function(){return"none"===this.corsMetadata.corsType?
null:new window[this.corsMetadata.corsType]},submitRequest:function(c){q.registerRequest(D.createQueuedRequest(c));return!0},createQueuedRequest:function(c){var a=q,l,f=c.callback,d="img",e;if(!x.isEmptyObject(s)){var b,h,g;for(b in s)if(s.hasOwnProperty(b)&&(h=s[b],!(null==h||""===h)&&b in c&&!(h in c)&&!(h in q.reservedKeys)))g=c[b],null==g||""===g||(c[h]=g)}x.isValidPdata(c.sids)||(c.sids=[]);x.isValidPdata(c.pdata)||(c.pdata=[]);x.isValidLogdata(c.logdata)||(c.logdata={});c.logdataArray=u.convertObjectToKeyValuePairs(c.logdata,
"\x3d",!0);c.logdataArray.push("_ts\x3d"+(new Date).getTime());"function"!==typeof f&&(f=this.defaultCallback);a.useJSONP=!0!==c.useImageRequest;a.useJSONP&&(d="script",l=a.callbackPrefix+"_"+k+"_"+(new Date).getTime());a=this.makeRequestSrcData(c,l);if((!P||F)&&(e=this.getCORSInstance()))d="cors";return{tag:d,src:a.src,corsSrc:a.corsSrc,internalCallbackName:l,callbackFn:f,postCallbackFn:c.postCallbackFn,useImageRequest:!!c.useImageRequest,requestData:c,corsInstance:e,corsPostData:a.corsPostData}},
defaultCallback:function(c,a){var l,f,d,b,e,h,g,k,t;if((l=c.stuff)&&l instanceof Array&&(f=l.length))for(d=0;d<f;d++)if((b=l[d])&&b===Object(b)){e=b.cn;h=b.cv;g=b.ttl;if("undefined"===typeof g||""===g)g=Math.floor(u.getMaxCookieExpiresInMinutes()/60/24);k=b.dmn||"."+document.domain.replace(/^www\./,"");t=b.type;if(e&&(h||"number"===typeof h))"var"!==t&&(g=parseInt(g,10))&&!isNaN(g)&&u.setCookie(e,h,1440*g,"/",k,!1),J.stuffed[e]=h}l=c.uuid;if(x.isPopulatedString(l)&&!x.isEmptyObject(n)){f=n.path;if("string"!==
typeof f||!f.length)f="/";d=parseInt(n.days,10);isNaN(d)&&(d=100);u.setCookie(n.name||"aam_did",l,1440*d,f,n.domain||"."+document.domain.replace(/^www\./,""),!0===n.secure)}!r&&!q.abortRequests&&y.requestToProcess(c,a)},makeRequestSrcData:function(c,a){c.sids=x.removeEmptyArrayValues(c.sids||[]);c.pdata=x.removeEmptyArrayValues(c.pdata||[]);var d=q,f=d.platformParams,b=u.encodeAndBuildRequest(c.sids,","),e=u.encodeAndBuildRequest(c.pdata,","),g=(c.logdataArray||[]).join("\x26");delete c.logdataArray;
var n=z.IS_HTTPS?"https://":"http://",t=d.declaredId.getDeclaredIdQueryString(),w=d.adms.instance?d.adms.getCustomerIDsQueryString(d.adms.getCustomerIDs()):"",s;s=[];var p,r,v,A;for(p in c)if(!(p in d.reservedKeys)&&c.hasOwnProperty(p))if(r=c[p],p=encodeURIComponent(p),r instanceof Array){v=0;for(A=r.length;v<A;v++)s.push(p+"\x3d"+encodeURIComponent(r[v]))}else s.push(p+"\x3d"+encodeURIComponent(r));s=s.length?"\x26"+s.join("\x26"):"";b="d_nsid\x3d"+f.d_nsid+t+w+(b.length?"\x26d_sid\x3d"+b:"")+(e.length?
"\x26d_px\x3d"+e:"")+(g.length?"\x26d_ld\x3d"+encodeURIComponent(g):"");f="\x26d_rtbd\x3d"+f.d_rtbd+"\x26d_jsonv\x3d"+f.d_jsonv+"\x26d_dst\x3d"+f.d_dst;n=n+h+".demdex.net/event";e=d=n+"?"+b+(d.useJSONP?f+"\x26d_cb\x3d"+(a||""):"")+s;2048<d.length&&(d=d.substring(0,2048).substring(0,d.lastIndexOf("\x26")));return{corsSrc:n+"?"+(O?"testcors\x3d1\x26d_nsid\x3d"+k+"\x26":"")+"_ts\x3d"+(new Date).getTime(),src:d,originalSrc:e,corsPostData:b+f+s,isDeclaredIdCall:""!==t}},fireRequest:function(c){if("img"===
c.tag)this.fireImage(c);else{var a=q.declaredId,a=a.declaredId.request||a.declaredId.init||{},a={dpid:a.dpid||"",dpuuid:a.dpuuid||""};"script"===c.tag?this.fireScript(c,a):"cors"===c.tag&&this.fireCORS(c,a)}},fireImage:function(c){var a=q,b,f;a.abortRequests||(a.firing=!0,b=new Image(0,0),a.sent.push(c),b.onload=function(){a.firing=!1;a.fired.push(c);a.num_of_img_responses++;a.registerRequest()},f=function(f){d="imgAbortOrErrorHandler received the event of type "+f.type;e.push(d);a.abortRequests=
!0;a.firing=!1;a.errored.push(c);a.num_of_img_errors++;a.registerRequest()},b.addEventListener?(b.addEventListener("error",f,!1),b.addEventListener("abort",f,!1)):b.attachEvent&&(b.attachEvent("onerror",f),b.attachEvent("onabort",f)),b.src=c.src)},fireScript:function(c,a){var b=this,f=q,g,k,n=c.src,t=c.postCallbackFn,s="function"===typeof t,w=c.internalCallbackName;f.abortRequests||(f.firing=!0,window[w]=function(b){try{b!==Object(b)&&(b={});B&&(y.ibsDeleted.push(b.ibs),delete b.ibs);var l=c.callbackFn;
f.firing=!1;f.fired.push(c);f.num_of_jsonp_responses++;l(b,a);s&&t(b,a)}catch(g){g.message="DIL jsonp callback caught error with message "+g.message;d=g.message;e.push(d);g.filename=g.filename||"dil.js";g.partner=h;DIL.errorModule.handleError(g);try{l({error:g.name+"|"+g.message},a),s&&t({error:g.name+"|"+g.message},a)}catch(n){}}finally{f.requestRemoval({script:k,callbackName:w}),f.registerRequest()}},!M&&!F?(k=document.createElement("script"),k.addEventListener&&k.addEventListener("error",function(a){f.requestRemoval({script:k,
callbackName:w});d="jsonp script tag error listener received the event of type "+a.type+" with src "+n;b.handleScriptError(d,c)},!1),k.type="text/javascript",k.src=n,g=DIL.variables.scriptNodeList[0],g.parentNode.insertBefore(k,g)):(f.firing=!1,f.requestRemoval({script:"no script created",callbackName:w})),f.sent.push(c),f.declaredId.declaredId.request=null)},fireCORS:function(c,a){var b=this,f=q,g=this.corsMetadata.corsType,k=c.corsSrc,n=c.corsInstance,t=c.corsPostData,w=c.postCallbackFn,s="function"===
typeof w;if(!f.abortRequests&&!R){f.firing=!0;try{n.open("post",k,!0),"XMLHttpRequest"===g&&(n.withCredentials=!0,n.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),n.onreadystatechange=function(){if(4===this.readyState&&200===this.status)a:{var g;try{if(g=JSON.parse(this.responseText),g!==Object(g)){b.handleCORSError(c,a,"Response is not JSON");break a}}catch(k){b.handleCORSError(c,a,"Error parsing response as JSON");break a}B&&(y.ibsDeleted.push(g.ibs),delete g.ibs);try{var n=
c.callbackFn;f.firing=!1;f.fired.push(c);f.num_of_cors_responses++;n(g,a);s&&w(g,a)}catch(t){t.message="DIL handleCORSResponse caught error with message "+t.message;d=t.message;e.push(d);t.filename=t.filename||"dil.js";t.partner=h;DIL.errorModule.handleError(t);try{n({error:t.name+"|"+t.message},a),s&&w({error:t.name+"|"+t.message},a)}catch(p){}}finally{f.registerRequest()}}}),n.onerror=function(){b.handleCORSError(c,a,"onerror")},n.ontimeout=function(){b.handleCORSError(c,a,"ontimeout")},n.send(t)}catch(p){this.handleCORSError(c,
a,"try-catch")}f.sent.push(c);f.declaredId.declaredId.request=null}},handleCORSError:function(c,a,b){q.num_of_cors_errors++;q.corsErrorSources.push(b);"ontimeout"!==b&&!F&&(c.tag="script",this.fireScript(c,a))},handleScriptError:function(c,a){q.num_of_jsonp_errors++;this.handleRequestError(c,a)},handleRequestError:function(c,a){var b=q;e.push(c);b.abortRequests=!0;b.firing=!1;b.errored.push(a);b.registerRequest()}},x={isValidPdata:function(a){return a instanceof Array&&this.removeEmptyArrayValues(a).length?
!0:!1},isValidLogdata:function(a){return!this.isEmptyObject(a)},isEmptyObject:function(a){if(a!==Object(a))return!0;for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},removeEmptyArrayValues:function(a){for(var b=0,d=a.length,f,e=[],b=0;b<d;b++)f=a[b],"undefined"!==typeof f&&(null!==f&&""!==f)&&e.push(f);return e},isPopulatedString:function(a){return"string"===typeof a&&a.length}},u={addListener:function(){if(document.addEventListener)return function(a,b,d){a.addEventListener(b,function(a){"function"===
typeof d&&d(a)},!1)};if(document.attachEvent)return function(a,b,d){a.attachEvent("on"+b,function(a){"function"===typeof d&&d(a)})}}(),convertObjectToKeyValuePairs:function(a,b,d){var f=[],e,g;b||(b="\x3d");for(e in a)a.hasOwnProperty(e)&&(g=a[e],"undefined"!==typeof g&&(null!==g&&""!==g)&&f.push(e+b+(d?encodeURIComponent(g):g)));return f},encodeAndBuildRequest:function(a,b){return this.map(a,function(a){return encodeURIComponent(a)}).join(b)},map:function(a,b){if(Array.prototype.map)return a.map(b);
if(void 0===a||null===a)throw new TypeError;var d=Object(a),f=d.length>>>0;if("function"!==typeof b)throw new TypeError;for(var e=Array(f),g=0;g<f;g++)g in d&&(e[g]=b.call(b,d[g],g,d));return e},filter:function(a,b){if(!Array.prototype.filter){if(void 0===a||null===a)throw new TypeError;var d=Object(a),f=d.length>>>0;if("function"!==typeof b)throw new TypeError;for(var e=[],g=0;g<f;g++)if(g in d){var h=d[g];b.call(b,h,g,d)&&e.push(h)}return e}return a.filter(b)},getCookie:function(a){a+="\x3d";var b=
document.cookie.split(";"),d,f,e;d=0;for(f=b.length;d<f;d++){for(e=b[d];" "===e.charAt(0);)e=e.substring(1,e.length);if(0===e.indexOf(a))return decodeURIComponent(e.substring(a.length,e.length))}return null},setCookie:function(a,b,d,f,e,g){var h=new Date;d&&(d*=6E4);document.cookie=a+"\x3d"+encodeURIComponent(b)+(d?";expires\x3d"+(new Date(h.getTime()+d)).toUTCString():"")+(f?";path\x3d"+f:"")+(e?";domain\x3d"+e:"")+(g?";secure":"")},extendArray:function(a,b){return a instanceof Array&&b instanceof
Array?(Array.prototype.push.apply(a,b),!0):!1},extendObject:function(a,b,d){var f;if(a===Object(a)&&b===Object(b)){for(f in b)if(b.hasOwnProperty(f)&&(x.isEmptyObject(d)||!(f in d)))a[f]=b[f];return!0}return!1},getMaxCookieExpiresInMinutes:function(){return((new Date(z.COOKIE_MAX_EXPIRATION_DATE)).getTime()-(new Date).getTime())/1E3/60}};"error"===h&&0===k&&u.addListener(window,"load",function(){DIL.windowLoaded=!0});var S=!1,H=function(){S||(S=!0,q.registerRequest(),U(),!r&&!q.abortRequests&&y.attachIframe(),
q.readyToRemove=!0,q.requestRemoval())},U=function(){r||setTimeout(function(){!N&&!q.firstRequestHasFired&&("function"===typeof I?K.afterResult(I).submit():K.submit())},DIL.constants.TIME_TO_DEFAULT_REQUEST)};C=document;"error"!==h&&(DIL.windowLoaded?H():"complete"!==C.readyState&&"loaded"!==C.readyState?u.addListener(window,"load",function(){DIL.windowLoaded=!0;H()}):(DIL.windowLoaded=!0,H()));q.declaredId.setDeclaredId(t,"init");q.processVisitorAPI();this.api=K;this.getStuffedVariable=function(a){var b=
J.stuffed[a];!b&&"number"!==typeof b&&(b=u.getCookie(a),!b&&"number"!==typeof b&&(b=""));return b};this.validators=x;this.helpers=u;this.constants=z;this.log=e;T&&(this.pendingRequest=p,this.requestController=q,this.setDestinationPublishingUrl=g,this.destinationPublishing=y,this.requestProcs=D,this.variables=J,this.callWindowLoadFunctions=H)},function(){var a=document,b;null==a.readyState&&a.addEventListener&&(a.readyState="loading",a.addEventListener("DOMContentLoaded",b=function(){a.removeEventListener("DOMContentLoaded",
b,!1);a.readyState="complete"},!1))}(),DIL.extendStaticPropertiesAndMethods=function(a){var b;if(a===Object(a))for(b in a)a.hasOwnProperty(b)&&(this[b]=a[b])},DIL.extendStaticPropertiesAndMethods({version:"6.5",jsonVersion:1,constants:{TIME_TO_DEFAULT_REQUEST:50},variables:{scriptNodeList:document.getElementsByTagName("script"),scriptsRemoved:[],callbacksRemoved:[]},windowLoaded:!1,dils:{},isAddedPostWindowLoad:function(a){this.windowLoaded="function"===typeof a?!!a():"boolean"===typeof a?a:!0},create:function(a){try{return new DIL(a)}catch(b){return(new Image(0,
0)).src="http://error.demdex.net/event?d_nsid\x3d0\x26d_px\x3d14137\x26d_ld\x3dname%3Derror%26filename%3Ddil.js%26partner%3Dno_partner%26message%3DError%2520in%2520attempt%2520to%2520create%2520DIL%2520instance%2520with%2520DIL.create()%26_ts%3D"+(new Date).getTime(),Error("Error in attempt to create DIL instance with DIL.create()")}},registerDil:function(a,b,e){b=b+"$"+e;b in this.dils||(this.dils[b]=a)},getDil:function(a,b){var e;"string"!==typeof a&&(a="");b||(b=0);e=a+"$"+b;return e in this.dils?
this.dils[e]:Error("The DIL instance with partner \x3d "+a+" and containerNSID \x3d "+b+" was not found")},dexGetQSVars:function(a,b,e){b=this.getDil(b,e);return b instanceof this?b.getStuffedVariable(a):""},xd:{postMessage:function(a,b,e){var d=1;b&&(window.postMessage?e.postMessage(a,b.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):b&&(e.location=b.replace(/#.*$/,"")+"#"+ +new Date+d++ +"\x26"+a))}}}),DIL.errorModule=function(){var a=DIL.create({partner:"error",containerNSID:0,disableDestinationPublishingIframe:!0}),
b={harvestererror:14138,destpuberror:14139,dpmerror:14140,generalerror:14137,error:14137,noerrortypedefined:15021,evalerror:15016,rangeerror:15017,referenceerror:15018,typeerror:15019,urierror:15020},e=!1;return{activate:function(){e=!0},handleError:function(d){if(!e)return"DIL error module has not been activated";d!==Object(d)&&(d={});var g=d.name?(d.name+"").toLowerCase():"",h=[];d={name:g,filename:d.filename?d.filename+"":"",partner:d.partner?d.partner+"":"no_partner",site:d.site?d.site+"":document.location.href,
message:d.message?d.message+"":""};h.push(g in b?b[g]:b.noerrortypedefined);a.api.pixels(h).logs(d).useImageRequest().submit();return"DIL error report sent"},pixelMap:b}}(),DIL.tools={},DIL.modules={helpers:{handleModuleError:function(a,b,e){var d="";b=b||"Error caught in DIL module/submodule: ";a===Object(a)?d=b+(a.message||"err has no message"):(d=b+"err is not a valid object",a={});a.message=d;e instanceof DIL&&(a.partner=e.api.getPartner());DIL.errorModule.handleError(a);return this.errorMessage=
d}}});
DIL.tools.getSearchReferrer=function(a,b){var e=DIL.getDil("error"),d=DIL.tools.decomposeURI(a||document.referrer),g="",h="",k={queryParam:"q"},g=e.helpers.filter([b===Object(b)?b:{},{hostPattern:/aol\./},{hostPattern:/ask\./},{hostPattern:/bing\./},{hostPattern:/google\./},{hostPattern:/yahoo\./,queryParam:"p"}],function(a){return!(!a.hasOwnProperty("hostPattern")||!d.hostname.match(a.hostPattern))}).shift();return!g?{valid:!1,name:"",keywords:""}:{valid:!0,name:d.hostname,keywords:(e.helpers.extendObject(k,g),
h=k.queryPattern?(g=(""+d.search).match(k.queryPattern))?g[1]:"":d.uriParams[k.queryParam],decodeURIComponent(h||"").replace(/\+|%20/g," "))}};
DIL.tools.decomposeURI=function(a){var b=DIL.getDil("error"),e=document.createElement("a");e.href=a||document.referrer;return{hash:e.hash,host:e.host.split(":").shift(),hostname:e.hostname,href:e.href,pathname:e.pathname.replace(/^\//,""),protocol:e.protocol,search:e.search,uriParams:function(a,e){b.helpers.map(e.split("\x26"),function(b){b=b.split("\x3d");a[b.shift()]=b.shift()});return a}({},e.search.replace(/^(\/|\?)?|\/$/g,""))}};
DIL.tools.getMetaTags=function(){var a={},b=document.getElementsByTagName("meta"),e,d,g,h,k;e=0;for(g=arguments.length;e<g;e++)if(h=arguments[e],null!==h)for(d=0;d<b.length;d++)if(k=b[d],k.name===h){a[h]=k.content;break}return a};
DIL.modules.siteCatalyst={dil:null,handle:DIL.modules.helpers.handleModuleError,init:function(a,b,e,d){try{var g=this,h={name:"DIL Site Catalyst Module Error"},k=function(a){h.message=a;DIL.errorModule.handleError(h);return a};this.options=d===Object(d)?d:{};this.dil=null;if(b instanceof DIL)this.dil=b;else return k("dilInstance is not a valid instance of DIL");h.partner=b.api.getPartner();if(a!==Object(a))return k("siteCatalystReportingSuite is not an object");window.AppMeasurement_Module_DIL=a.m_DIL=
function(a){var b="function"===typeof a.m_i?a.m_i("DIL"):this;if(b!==Object(b))return k("m is not an object");b.trackVars=g.constructTrackVars(e);b.d=0;b.s=a;b._t=function(){var a,b,d=","+this.trackVars+",",e=this.s,h,s=[];h=[];var r={},v=!1;if(e!==Object(e))return k("Error in m._t function: s is not an object");if(this.d){if("function"===typeof e.foreachVar)e.foreachVar(function(a,b){"undefined"!==typeof b&&(r[a]=b,v=!0)},this.trackVars);else{if(!(e.va_t instanceof Array))return k("Error in m._t function: s.va_t is not an array");
if(e.lightProfileID)(a=e.lightTrackVars)&&(a=","+a+","+e.vl_mr+",");else if(e.pe||e.linkType)a=e.linkTrackVars,e.pe&&(b=e.pe.substring(0,1).toUpperCase()+e.pe.substring(1),e[b]&&(a=e[b].trackVars)),a&&(a=","+a+","+e.vl_l+","+e.vl_l2+",");if(a){b=0;for(s=a.split(",");b<s.length;b++)0<=d.indexOf(","+s[b]+",")&&h.push(s[b]);h.length&&(d=","+h.join(",")+",")}h=0;for(b=e.va_t.length;h<b;h++)a=e.va_t[h],0<=d.indexOf(","+a+",")&&("undefined"!==typeof e[a]&&null!==e[a]&&""!==e[a])&&(r[a]=e[a],v=!0)}g.includeContextData(e,
r).store_populated&&(v=!0);v&&this.d.api.signals(r,"c_").submit()}}};a.loadModule("DIL");a.DIL.d=b;return h.message?h.message:"DIL.modules.siteCatalyst.init() completed with no errors"}catch(r){return this.handle(r,"DIL.modules.siteCatalyst.init() caught error with message ",this.dil)}},constructTrackVars:function(a){var b=[],e,d,g,h,k;if(a===Object(a)){e=a.names;if(e instanceof Array&&(g=e.length))for(d=0;d<g;d++)h=e[d],"string"===typeof h&&h.length&&b.push(h);a=a.iteratedNames;if(a instanceof Array&&
(g=a.length))for(d=0;d<g;d++)if(e=a[d],e===Object(e)&&(h=e.name,k=parseInt(e.maxIndex,10),"string"===typeof h&&h.length&&!isNaN(k)&&0<=k))for(e=0;e<=k;e++)b.push(h+e);if(b.length)return b.join(",")}return this.constructTrackVars({names:"pageName channel campaign products events pe pev1 pev2 pev3".split(" "),iteratedNames:[{name:"prop",maxIndex:75},{name:"eVar",maxIndex:250}]})},includeContextData:function(a,b){var e={},d=!1;if(a.contextData===Object(a.contextData)){var g=a.contextData,h=this.options.replaceContextDataPeriodsWith,
k=this.options.filterFromContextVariables,r={},v,s,n,w;if("string"!==typeof h||!h.length)h="_";if(k instanceof Array){v=0;for(s=k.length;v<s;v++)n=k[v],this.dil.validators.isPopulatedString(n)&&(r[n]=!0)}for(w in g)if(g.hasOwnProperty(w)&&!r[w]&&((k=g[w])||"number"===typeof k))w=("contextData."+w).replace(/\./g,h),b[w]=k,d=!0}e.store_populated=d;return e}};
DIL.modules.GA={dil:null,arr:null,tv:null,errorMessage:"",defaultTrackVars:["_setAccount","_setCustomVar","_addItem","_addTrans","_trackSocial"],defaultTrackVarsObj:null,signals:{},hasSignals:!1,handle:DIL.modules.helpers.handleModuleError,init:function(a,b,e){try{this.tv=this.arr=this.dil=null;this.errorMessage="";this.signals={};this.hasSignals=!1;var d={name:"DIL GA Module Error"},g="";b instanceof DIL?(this.dil=b,d.partner=this.dil.api.getPartner()):(g="dilInstance is not a valid instance of DIL",
d.message=g,DIL.errorModule.handleError(d));!(a instanceof Array)||!a.length?(g="gaArray is not an array or is empty",d.message=g,DIL.errorModule.handleError(d)):this.arr=a;this.tv=this.constructTrackVars(e);this.errorMessage=g}catch(h){this.handle(h,"DIL.modules.GA.init() caught error with message ",this.dil)}finally{return this}},constructTrackVars:function(a){var b=[],e,d,g,h;if(this.defaultTrackVarsObj!==Object(this.defaultTrackVarsObj)){g=this.defaultTrackVars;h={};e=0;for(d=g.length;e<d;e++)h[g[e]]=
!0;this.defaultTrackVarsObj=h}else h=this.defaultTrackVarsObj;if(a===Object(a)){a=a.names;if(a instanceof Array&&(d=a.length))for(e=0;e<d;e++)g=a[e],"string"===typeof g&&(g.length&&g in h)&&b.push(g);if(b.length)return b}return this.defaultTrackVars},constructGAObj:function(a){var b={};a=a instanceof Array?a:this.arr;var e,d,g,h;e=0;for(d=a.length;e<d;e++)g=a[e],g instanceof Array&&g.length&&(g=[],h=a[e],g instanceof Array&&h instanceof Array&&Array.prototype.push.apply(g,h),h=g.shift(),"string"===
typeof h&&h.length&&(b[h]instanceof Array||(b[h]=[]),b[h].push(g)));return b},addToSignals:function(a,b){if("string"!==typeof a||""===a||null==b||""===b)return!1;this.signals[a]instanceof Array||(this.signals[a]=[]);this.signals[a].push(b);return this.hasSignals=!0},constructSignals:function(){var a=this.constructGAObj(),b={_setAccount:function(a){this.addToSignals("c_accountId",a)},_setCustomVar:function(a,b,d){"string"===typeof b&&b.length&&this.addToSignals("c_"+b,d)},_addItem:function(a,b,d,e,
g,h){this.addToSignals("c_itemOrderId",a);this.addToSignals("c_itemSku",b);this.addToSignals("c_itemName",d);this.addToSignals("c_itemCategory",e);this.addToSignals("c_itemPrice",g);this.addToSignals("c_itemQuantity",h)},_addTrans:function(a,b,d,e,g,h,k,r){this.addToSignals("c_transOrderId",a);this.addToSignals("c_transAffiliation",b);this.addToSignals("c_transTotal",d);this.addToSignals("c_transTax",e);this.addToSignals("c_transShipping",g);this.addToSignals("c_transCity",h);this.addToSignals("c_transState",
k);this.addToSignals("c_transCountry",r)},_trackSocial:function(a,b,d,e){this.addToSignals("c_socialNetwork",a);this.addToSignals("c_socialAction",b);this.addToSignals("c_socialTarget",d);this.addToSignals("c_socialPagePath",e)}},e=this.tv,d,g,h,k,r,v;d=0;for(g=e.length;d<g;d++)if(h=e[d],a.hasOwnProperty(h)&&b.hasOwnProperty(h)&&(v=a[h],v instanceof Array)){k=0;for(r=v.length;k<r;k++)b[h].apply(this,v[k])}},submit:function(){try{if(""!==this.errorMessage)return this.errorMessage;this.constructSignals();
return this.hasSignals?(this.dil.api.signals(this.signals).submit(),"Signals sent: "+this.dil.helpers.convertObjectToKeyValuePairs(this.signals,"\x3d",!0)+this.dil.log):"No signals present"}catch(a){return this.handle(a,"DIL.modules.GA.submit() caught error with message ",this.dil)}},Stuffer:{LIMIT:5,dil:null,cookieName:null,delimiter:null,errorMessage:"",handle:DIL.modules.helpers.handleModuleError,callback:null,v:function(){return!1},init:function(a,b,e){try{this.callback=this.dil=null,this.errorMessage=
"",a instanceof DIL?(this.dil=a,this.v=this.dil.validators.isPopulatedString,this.cookieName=this.v(b)?b:"aam_ga",this.delimiter=this.v(e)?e:"|"):this.handle({message:"dilInstance is not a valid instance of DIL"},"DIL.modules.GA.Stuffer.init() error: ")}catch(d){this.handle(d,"DIL.modules.GA.Stuffer.init() caught error with message ",this.dil)}finally{return this}},process:function(a){var b,e,d,g,h,k;k=!1;var r=1;if(a===Object(a)&&(b=a.stuff)&&b instanceof Array&&(e=b.length))for(a=0;a<e;a++)if((d=
b[a])&&d===Object(d))if(g=d.cn,h=d.cv,g===this.cookieName&&this.v(h)){k=!0;break}if(k){b=h.split(this.delimiter);"undefined"===typeof window._gaq&&(window._gaq=[]);d=window._gaq;a=0;for(e=b.length;a<e&&!(k=b[a].split("\x3d"),h=k[0],k=k[1],this.v(h)&&this.v(k)&&d.push(["_setCustomVar",r++,h,k,1]),r>this.LIMIT);a++);this.errorMessage=1<r?"No errors - stuffing successful":"No valid values to stuff"}else this.errorMessage="Cookie name and value not found in json";if("function"===typeof this.callback)return this.callback()},
submit:function(){try{var a=this;if(""!==this.errorMessage)return this.errorMessage;this.dil.api.afterResult(function(b){a.process(b)}).submit();return"DIL.modules.GA.Stuffer.submit() successful"}catch(b){return this.handle(b,"DIL.modules.GA.Stuffer.submit() caught error with message ",this.dil)}}}};